displayName=Prayer Overheads Reworked
author=wrgracey
description=Hide or restyle the large overhead protection prayer bubbles
tags=prayer,overhead,hide,raid,declutter
version=
plugins=com.prayeroverheads.PrayerOverheadsPlugin
build=standard
