displayName=Prayer Overheads Reworked
author=wrgracey
description=Replace the large overhead protection prayer bubbles with a subtle display
tags=prayer,overhead,hide,raid,declutter
version=1.0.0
plugins=com.prayeroverheads.PrayerOverheadsPlugin
build=standard
